[profile.default]
via_ir = true
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.17'

remappings = [
    'forge-std=lib/forge-std/src/',
]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.test]
solc = '0.8.18'
cbor_metadata = false
optimizer_details.yulDetails.stackAllocation = true
optimizer_details.yulDetails.optimizerSteps = ''
